//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Parking.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Car_Parking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОДТВЕРДИТЬ.
        /// </summary>
        internal static string accept_button_blank {
            get {
                return ResourceManager.GetString("accept_button_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВСЕ АВТО.
        /// </summary>
        internal static string all_auto {
            get {
                return ResourceManager.GetString("all auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АВТОСТОЯНКА.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МАШИНА.
        /// </summary>
        internal static string car {
            get {
                return ResourceManager.GetString("car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер авто :.
        /// </summary>
        internal static string car_number {
            get {
                return ResourceManager.GetString("car_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регион :.
        /// </summary>
        internal static string car_region {
            get {
                return ResourceManager.GetString("car_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серия :.
        /// </summary>
        internal static string car_series {
            get {
                return ResourceManager.GetString("car_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный номер авто.
        /// </summary>
        internal static string carNumberEmpty {
            get {
                return ResourceManager.GetString("carNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный регион.
        /// </summary>
        internal static string carRegionEmpty {
            get {
                return ResourceManager.GetString("carRegionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректная серия авто.
        /// </summary>
        internal static string carSeriesEmpty {
            get {
                return ResourceManager.GetString("carSeriesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный сектор.
        /// </summary>
        internal static string carSpaceEmpty {
            get {
                return ResourceManager.GetString("carSpaceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не менее 6 символов.
        /// </summary>
        internal static string charac {
            get {
                return ResourceManager.GetString("charac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напишите коментарий.
        /// </summary>
        internal static string comment_example {
            get {
                return ResourceManager.GetString("comment_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают.
        /// </summary>
        internal static string eaqfield {
            get {
                return ResourceManager.GetString("eaqfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните поле пароля.
        /// </summary>
        internal static string emptyfield {
            get {
                return ResourceManager.GetString("emptyfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните поле имени.
        /// </summary>
        internal static string emptyfieldlogin {
            get {
                return ResourceManager.GetString("emptyfieldlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        internal static string Enter_name {
            get {
                return ResourceManager.GetString("Enter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите номер телефона :.
        /// </summary>
        internal static string enter_phone {
            get {
                return ResourceManager.GetString("enter phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой пользователь уже существует.
        /// </summary>
        internal static string existserr {
            get {
                return ResourceManager.GetString("existserr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните поля :.
        /// </summary>
        internal static string fillAdminPage {
            get {
                return ResourceManager.GetString("fillAdminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИСТОРИЯ.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГЛАВНАЯ.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время начала аренды :.
        /// </summary>
        internal static string lease_time {
            get {
                return ResourceManager.GetString("lease_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное время.
        /// </summary>
        internal static string leaseTimeEmpty {
            get {
                return ResourceManager.GetString("leaseTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефона.
        /// </summary>
        internal static string login_name {
            get {
                return ResourceManager.GetString("login_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РУС.
        /// </summary>
        internal static string mainwindow_language_button {
            get {
                return ResourceManager.GetString("mainwindow_language_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на такого пользователя не существует.
        /// </summary>
        internal static string nosuchuser {
            get {
                return ResourceManager.GetString("nosuchuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        internal static string pass_name {
            get {
                return ResourceManager.GetString("pass_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный пароль.
        /// </summary>
        internal static string passwordFail {
            get {
                return ResourceManager.GetString("passwordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма к оплате :.
        /// </summary>
        internal static string payAmountSum {
            get {
                return ResourceManager.GetString("payAmountSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОПЛАТА.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефона :.
        /// </summary>
        internal static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный номер телефона.
        /// </summary>
        internal static string phoneNumberEmpty {
            get {
                return ResourceManager.GetString("phoneNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегестрироваться.
        /// </summary>
        internal static string reg_name {
            get {
                return ResourceManager.GetString("reg_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль.
        /// </summary>
        internal static string rep_pass_name {
            get {
                return ResourceManager.GetString("rep_pass_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Открытые парковки г. Минска функционируют в платном режиме и делятся на сектора..
        /// </summary>
        internal static string rule_1 {
            get {
                return ResourceManager.GetString("rule_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. На каждом секторе цена отличается..
        /// </summary>
        internal static string rule_2 {
            get {
                return ResourceManager.GetString("rule_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. На парковке строго запрещается мусорить и препятствовать правильному размещению автомобилей..
        /// </summary>
        internal static string rule_3 {
            get {
                return ResourceManager.GetString("rule_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4. Оплата за использование парковки происходит на выезде..
        /// </summary>
        internal static string rule_4 {
            get {
                return ResourceManager.GetString("rule_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила пользования парковкой.
        /// </summary>
        internal static string rules_lable {
            get {
                return ResourceManager.GetString("rules_lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОИСК.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор A.
        /// </summary>
        internal static string sector_A {
            get {
                return ResourceManager.GetString("sector A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор B.
        /// </summary>
        internal static string sector_B {
            get {
                return ResourceManager.GetString("sector B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор С.
        /// </summary>
        internal static string sector_C {
            get {
                return ResourceManager.GetString("sector C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор D.
        /// </summary>
        internal static string sector_D {
            get {
                return ResourceManager.GetString("sector D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сектор :.
        /// </summary>
        internal static string space {
            get {
                return ResourceManager.GetString("space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время проведенное на стоянке :.
        /// </summary>
        internal static string timeOnParking {
            get {
                return ResourceManager.GetString("timeOnParking", resourceCulture);
            }
        }
    }
}
