//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Parking.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Car_Parking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОДТВЕРДИТЬ.
        /// </summary>
        internal static string accept_button_blank {
            get {
                return ResourceManager.GetString("accept_button_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер авто :.
        /// </summary>
        internal static string car_number {
            get {
                return ResourceManager.GetString("car_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регион :.
        /// </summary>
        internal static string car_region {
            get {
                return ResourceManager.GetString("car_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серия :.
        /// </summary>
        internal static string car_series {
            get {
                return ResourceManager.GetString("car_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коментарий :.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напишите коментарий.
        /// </summary>
        internal static string comment_example {
            get {
                return ResourceManager.GetString("comment_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время аренды :.
        /// </summary>
        internal static string lease_time {
            get {
                return ResourceManager.GetString("lease_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РУС.
        /// </summary>
        internal static string mainwindow_language_button {
            get {
                return ResourceManager.GetString("mainwindow_language_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефона :.
        /// </summary>
        internal static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Открытые парковки г. Минска функционируют в платном режиме в будние дни с 09.00 до 18.00. В остальное время, а также в выходные и праздничные дни – парковка бесплатна..
        /// </summary>
        internal static string rule_1 {
            get {
                return ResourceManager.GetString("rule_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. Способы оплаты на различных парковках могут отличаться..
        /// </summary>
        internal static string rule_2 {
            get {
                return ResourceManager.GetString("rule_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. После размещения транспортного средства на парковочном месте на территории платной автомобильной парковки необходимо осуществить оплату..
        /// </summary>
        internal static string rule_3 {
            get {
                return ResourceManager.GetString("rule_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4. Покинуть парковочное место необходимо незамедлительно после истечения сеанса парковки (оплаченного времени)..
        /// </summary>
        internal static string rule_4 {
            get {
                return ResourceManager.GetString("rule_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила пользования парковкой.
        /// </summary>
        internal static string rules_lable {
            get {
                return ResourceManager.GetString("rules_lable", resourceCulture);
            }
        }
    }
}
